// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItemSrc: typeof import('./src/components/ArticleItem/src/Index.vue')['default']
    BaseChartSrc: typeof import('./src/components/BaseChart/src/Index.vue')['default']
    BaseDrawerSrc: typeof import('./src/components/BaseDrawer/src/Index.vue')['default']
    BaseGridSrc: typeof import('./src/components/BaseGrid/src/Index.vue')['default']
    CircleImgSrc: typeof import('./src/components/CircleImg/src/Index.vue')['default']
    CustRouterViewSrc: typeof import('./src/components/CustRouterView/src/Index.vue')['default']
    DotSrc: typeof import('./src/components/Dot/src/Index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconButtonSrc: typeof import('./src/components/IconButton/src/Index.vue')['default']
    IconFontSrc: typeof import('./src/components/IconFont/src/Index.vue')['default']
    ListItemSrc: typeof import('./src/components/ListItem/src/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSrc: typeof import('./src/components/Search/src/Index.vue')['default']
    SimpleSearchSrc: typeof import('./src/components/SimpleSearch/src/Index.vue')['default']
    TitlePanelSrc: typeof import('./src/components/TitlePanel/src/Index.vue')['default']
    UserItemSrc: typeof import('./src/components/UserItem/src/Index.vue')['default']
  }
}

export {}
